# Generated by Django 4.1.7 on 2023-02-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30, verbose_name='Имя автора')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта автора записи')),
                ('text', models.TextField(verbose_name='Текст записи')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Время создания')),
                ('updated_date', models.DateTimeField(verbose_name='Время редактирования')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('blocked', 'Заблокировано')], default='active', max_length=50, verbose_name='Статус')),
            ],
        ),
    ]
