# Generated by Django 4.1.7 on 2023-02-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='updated_date',
            field=models.DateTimeField(null=True, verbose_name='Время редактирования'),
        ),
    ]
